#!/bin/bash
# Quick access to all dashboards and APIs

echo "=================================="
echo "NT-TRAFFIC-FILTER · QUICK ACCESS"
echo "=================================="
echo ""
echo "1️⃣  PRIMARY DASHBOARD (REST API)"
echo "   → http://localhost:8000/health"
echo ""
echo "2️⃣  KIBANA (Log Viewer)"
echo "   → http://localhost:5601"
echo "   Index: nt-detections-*"
echo ""
echo "3️⃣  GRAFANA (Metrics Dashboard)"
echo "   → http://localhost:3000"
echo ""
echo "4️⃣  PROMETHEUS (Raw Metrics)"
echo "   → http://localhost:9090"
echo ""
echo "5️⃣  ELASTICSEARCH (Direct Data)"
echo "   → http://localhost:9200"
echo ""
echo "=================================="
echo "API ENDPOINTS"
echo "=================================="
echo ""
echo "Health Check:"
echo "  curl http://localhost:8000/health"
echo ""
echo "Recent Detections:"
echo "  curl http://localhost:8000/detections?size=10"
echo ""
echo "Alerts:"
echo "  curl http://localhost:8000/alerts"
echo ""
echo "Stats:"
echo "  curl http://localhost:8000/stats"
echo ""
echo "=================================="
echo "LOGS"
echo "=================================="
echo ""
echo "Pipeline:  tail -f logs/pipeline.log"
echo "Generator: tail -f logs/generator.log"
echo "API:       tail -f logs/api.log"
echo ""
